### ISSUE TITLE
Error on anchor build

### ISSUE THREAD

**Issue by 0xPratik** [switchboard-xyz/sbv2-core#3]
Any idea how can we deal with this error. Been facing it every-time i try to play around with switchboard 

<img width="1200" alt="Screenshot 2023-01-12 at 3 27 37 PM" src="https://user-images.githubusercontent.com/62953475/212032676-deba01c4-68fa-49dc-83ba-cb73e59498a4.png">

**Comment by gallynaut** [comment]
Thanks for opening an issue, I thought this was an issue with my local config but seems to be global.

We pinned rust_decimal to 1.26.1 and verified the error has been resolved.
